/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterCompanyRouteImport } from './routes/register-company'
import { Route as ForEmployersRouteImport } from './routes/for-employers'
import { Route as ForCandidatesRouteImport } from './routes/for-candidates'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployerIndexRouteImport } from './routes/employer.index'
import { Route as CandidateIndexRouteImport } from './routes/candidate.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as GateEventIdRouteImport } from './routes/gate.$eventId'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as EmployerJobsRouteImport } from './routes/employer.jobs'
import { Route as EmployerInterviewsRouteImport } from './routes/employer.interviews'
import { Route as EmployerFeedbackRouteImport } from './routes/employer.feedback'
import { Route as EmployerEventsRouteImport } from './routes/employer.events'
import { Route as EmployerCompanyRouteImport } from './routes/employer.company'
import { Route as EmployerCandidatesRouteImport } from './routes/employer.candidates'
import { Route as EmployerAnalyticsRouteImport } from './routes/employer.analytics'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateJobsRouteImport } from './routes/candidate.jobs'
import { Route as CandidateInterviewsRouteImport } from './routes/candidate.interviews'
import { Route as CandidateHistoryRouteImport } from './routes/candidate.history'
import { Route as CandidateFeedbackRouteImport } from './routes/candidate.feedback'
import { Route as CandidateEventsRouteImport } from './routes/candidate.events'
import { Route as CandidateApplicationsRouteImport } from './routes/candidate.applications'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthAdminLoginRouteImport } from './routes/auth.admin-login'
import { Route as AttendPassIdRouteImport } from './routes/attend.$passId'
import { Route as AdminStallsRouteImport } from './routes/admin.stalls'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminQrRouteImport } from './routes/admin.qr'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminJobfairRouteImport } from './routes/admin.jobfair'
import { Route as AdminInterviewsRouteImport } from './routes/admin.interviews'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminEmployersRouteImport } from './routes/admin.employers'
import { Route as AdminDataRouteImport } from './routes/admin.data'
import { Route as AdminCompanyRequestsRouteImport } from './routes/admin.company-requests'
import { Route as AdminCollaborationRouteImport } from './routes/admin.collaboration'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as AdminAutomationRouteImport } from './routes/admin.automation'
import { Route as AdminAccessRouteImport } from './routes/admin.access'
import { Route as EmployerEventsIdRouteImport } from './routes/employer.events.$id'
import { Route as AdminAllocationEventIdRouteImport } from './routes/admin.allocation.$eventId'

const RegisterCompanyRoute = RegisterCompanyRouteImport.update({
  id: '/register-company',
  path: '/register-company',
  getParentRoute: () => rootRouteImport,
} as any)
const ForEmployersRoute = ForEmployersRouteImport.update({
  id: '/for-employers',
  path: '/for-employers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCandidatesRoute = ForCandidatesRouteImport.update({
  id: '/for-candidates',
  path: '/for-candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerIndexRoute = EmployerIndexRouteImport.update({
  id: '/employer/',
  path: '/employer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateIndexRoute = CandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const GateEventIdRoute = GateEventIdRouteImport.update({
  id: '/gate/$eventId',
  path: '/gate/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const EmployerJobsRoute = EmployerJobsRouteImport.update({
  id: '/employer/jobs',
  path: '/employer/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerInterviewsRoute = EmployerInterviewsRouteImport.update({
  id: '/employer/interviews',
  path: '/employer/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerFeedbackRoute = EmployerFeedbackRouteImport.update({
  id: '/employer/feedback',
  path: '/employer/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerEventsRoute = EmployerEventsRouteImport.update({
  id: '/employer/events',
  path: '/employer/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerCompanyRoute = EmployerCompanyRouteImport.update({
  id: '/employer/company',
  path: '/employer/company',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerCandidatesRoute = EmployerCandidatesRouteImport.update({
  id: '/employer/candidates',
  path: '/employer/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerAnalyticsRoute = EmployerAnalyticsRouteImport.update({
  id: '/employer/analytics',
  path: '/employer/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateJobsRoute = CandidateJobsRouteImport.update({
  id: '/candidate/jobs',
  path: '/candidate/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateInterviewsRoute = CandidateInterviewsRouteImport.update({
  id: '/candidate/interviews',
  path: '/candidate/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateHistoryRoute = CandidateHistoryRouteImport.update({
  id: '/candidate/history',
  path: '/candidate/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateFeedbackRoute = CandidateFeedbackRouteImport.update({
  id: '/candidate/feedback',
  path: '/candidate/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateEventsRoute = CandidateEventsRouteImport.update({
  id: '/candidate/events',
  path: '/candidate/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateApplicationsRoute = CandidateApplicationsRouteImport.update({
  id: '/candidate/applications',
  path: '/candidate/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdminLoginRoute = AuthAdminLoginRouteImport.update({
  id: '/auth/admin-login',
  path: '/auth/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendPassIdRoute = AttendPassIdRouteImport.update({
  id: '/attend/$passId',
  path: '/attend/$passId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStallsRoute = AdminStallsRouteImport.update({
  id: '/admin/stalls',
  path: '/admin/stalls',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQrRoute = AdminQrRouteImport.update({
  id: '/admin/qr',
  path: '/admin/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/admin/jobs',
  path: '/admin/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJobfairRoute = AdminJobfairRouteImport.update({
  id: '/admin/jobfair',
  path: '/admin/jobfair',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInterviewsRoute = AdminInterviewsRouteImport.update({
  id: '/admin/interviews',
  path: '/admin/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployersRoute = AdminEmployersRouteImport.update({
  id: '/admin/employers',
  path: '/admin/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin/data',
  path: '/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompanyRequestsRoute = AdminCompanyRequestsRouteImport.update({
  id: '/admin/company-requests',
  path: '/admin/company-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollaborationRoute = AdminCollaborationRouteImport.update({
  id: '/admin/collaboration',
  path: '/admin/collaboration',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/admin/candidates',
  path: '/admin/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAutomationRoute = AdminAutomationRouteImport.update({
  id: '/admin/automation',
  path: '/admin/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/admin/access',
  path: '/admin/access',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerEventsIdRoute = EmployerEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EmployerEventsRoute,
} as any)
const AdminAllocationEventIdRoute = AdminAllocationEventIdRouteImport.update({
  id: '/admin/allocation/$eventId',
  path: '/admin/allocation/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/for-candidates': typeof ForCandidatesRoute
  '/for-employers': typeof ForEmployersRoute
  '/register-company': typeof RegisterCompanyRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/collaboration': typeof AdminCollaborationRoute
  '/admin/company-requests': typeof AdminCompanyRequestsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/employers': typeof AdminEmployersRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/interviews': typeof AdminInterviewsRoute
  '/admin/jobfair': typeof AdminJobfairRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/qr': typeof AdminQrRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stalls': typeof AdminStallsRoute
  '/attend/$passId': typeof AttendPassIdRoute
  '/auth/admin-login': typeof AuthAdminLoginRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/events': typeof CandidateEventsRoute
  '/candidate/feedback': typeof CandidateFeedbackRoute
  '/candidate/history': typeof CandidateHistoryRoute
  '/candidate/interviews': typeof CandidateInterviewsRoute
  '/candidate/jobs': typeof CandidateJobsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/employer/analytics': typeof EmployerAnalyticsRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/company': typeof EmployerCompanyRoute
  '/employer/events': typeof EmployerEventsRouteWithChildren
  '/employer/feedback': typeof EmployerFeedbackRoute
  '/employer/interviews': typeof EmployerInterviewsRoute
  '/employer/jobs': typeof EmployerJobsRoute
  '/events/$id': typeof EventsIdRoute
  '/gate/$eventId': typeof GateEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/admin/allocation/$eventId': typeof AdminAllocationEventIdRoute
  '/employer/events/$id': typeof EmployerEventsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/for-candidates': typeof ForCandidatesRoute
  '/for-employers': typeof ForEmployersRoute
  '/register-company': typeof RegisterCompanyRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/collaboration': typeof AdminCollaborationRoute
  '/admin/company-requests': typeof AdminCompanyRequestsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/employers': typeof AdminEmployersRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/interviews': typeof AdminInterviewsRoute
  '/admin/jobfair': typeof AdminJobfairRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/qr': typeof AdminQrRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stalls': typeof AdminStallsRoute
  '/attend/$passId': typeof AttendPassIdRoute
  '/auth/admin-login': typeof AuthAdminLoginRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/events': typeof CandidateEventsRoute
  '/candidate/feedback': typeof CandidateFeedbackRoute
  '/candidate/history': typeof CandidateHistoryRoute
  '/candidate/interviews': typeof CandidateInterviewsRoute
  '/candidate/jobs': typeof CandidateJobsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/employer/analytics': typeof EmployerAnalyticsRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/company': typeof EmployerCompanyRoute
  '/employer/events': typeof EmployerEventsRouteWithChildren
  '/employer/feedback': typeof EmployerFeedbackRoute
  '/employer/interviews': typeof EmployerInterviewsRoute
  '/employer/jobs': typeof EmployerJobsRoute
  '/events/$id': typeof EventsIdRoute
  '/gate/$eventId': typeof GateEventIdRoute
  '/admin': typeof AdminIndexRoute
  '/candidate': typeof CandidateIndexRoute
  '/employer': typeof EmployerIndexRoute
  '/admin/allocation/$eventId': typeof AdminAllocationEventIdRoute
  '/employer/events/$id': typeof EmployerEventsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/for-candidates': typeof ForCandidatesRoute
  '/for-employers': typeof ForEmployersRoute
  '/register-company': typeof RegisterCompanyRoute
  '/admin/access': typeof AdminAccessRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/collaboration': typeof AdminCollaborationRoute
  '/admin/company-requests': typeof AdminCompanyRequestsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/employers': typeof AdminEmployersRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/interviews': typeof AdminInterviewsRoute
  '/admin/jobfair': typeof AdminJobfairRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/qr': typeof AdminQrRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stalls': typeof AdminStallsRoute
  '/attend/$passId': typeof AttendPassIdRoute
  '/auth/admin-login': typeof AuthAdminLoginRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/candidate/applications': typeof CandidateApplicationsRoute
  '/candidate/events': typeof CandidateEventsRoute
  '/candidate/feedback': typeof CandidateFeedbackRoute
  '/candidate/history': typeof CandidateHistoryRoute
  '/candidate/interviews': typeof CandidateInterviewsRoute
  '/candidate/jobs': typeof CandidateJobsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/employer/analytics': typeof EmployerAnalyticsRoute
  '/employer/candidates': typeof EmployerCandidatesRoute
  '/employer/company': typeof EmployerCompanyRoute
  '/employer/events': typeof EmployerEventsRouteWithChildren
  '/employer/feedback': typeof EmployerFeedbackRoute
  '/employer/interviews': typeof EmployerInterviewsRoute
  '/employer/jobs': typeof EmployerJobsRoute
  '/events/$id': typeof EventsIdRoute
  '/gate/$eventId': typeof GateEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/candidate/': typeof CandidateIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/admin/allocation/$eventId': typeof AdminAllocationEventIdRoute
  '/employer/events/$id': typeof EmployerEventsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/for-candidates'
    | '/for-employers'
    | '/register-company'
    | '/admin/access'
    | '/admin/automation'
    | '/admin/candidates'
    | '/admin/collaboration'
    | '/admin/company-requests'
    | '/admin/data'
    | '/admin/employers'
    | '/admin/events'
    | '/admin/feedback'
    | '/admin/interviews'
    | '/admin/jobfair'
    | '/admin/jobs'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/qr'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/stalls'
    | '/attend/$passId'
    | '/auth/admin-login'
    | '/auth/login'
    | '/auth/signup'
    | '/candidate/applications'
    | '/candidate/events'
    | '/candidate/feedback'
    | '/candidate/history'
    | '/candidate/interviews'
    | '/candidate/jobs'
    | '/candidate/profile'
    | '/employer/analytics'
    | '/employer/candidates'
    | '/employer/company'
    | '/employer/events'
    | '/employer/feedback'
    | '/employer/interviews'
    | '/employer/jobs'
    | '/events/$id'
    | '/gate/$eventId'
    | '/admin/'
    | '/candidate/'
    | '/employer/'
    | '/admin/allocation/$eventId'
    | '/employer/events/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/for-candidates'
    | '/for-employers'
    | '/register-company'
    | '/admin/access'
    | '/admin/automation'
    | '/admin/candidates'
    | '/admin/collaboration'
    | '/admin/company-requests'
    | '/admin/data'
    | '/admin/employers'
    | '/admin/events'
    | '/admin/feedback'
    | '/admin/interviews'
    | '/admin/jobfair'
    | '/admin/jobs'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/qr'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/stalls'
    | '/attend/$passId'
    | '/auth/admin-login'
    | '/auth/login'
    | '/auth/signup'
    | '/candidate/applications'
    | '/candidate/events'
    | '/candidate/feedback'
    | '/candidate/history'
    | '/candidate/interviews'
    | '/candidate/jobs'
    | '/candidate/profile'
    | '/employer/analytics'
    | '/employer/candidates'
    | '/employer/company'
    | '/employer/events'
    | '/employer/feedback'
    | '/employer/interviews'
    | '/employer/jobs'
    | '/events/$id'
    | '/gate/$eventId'
    | '/admin'
    | '/candidate'
    | '/employer'
    | '/admin/allocation/$eventId'
    | '/employer/events/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/for-candidates'
    | '/for-employers'
    | '/register-company'
    | '/admin/access'
    | '/admin/automation'
    | '/admin/candidates'
    | '/admin/collaboration'
    | '/admin/company-requests'
    | '/admin/data'
    | '/admin/employers'
    | '/admin/events'
    | '/admin/feedback'
    | '/admin/interviews'
    | '/admin/jobfair'
    | '/admin/jobs'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/qr'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/stalls'
    | '/attend/$passId'
    | '/auth/admin-login'
    | '/auth/login'
    | '/auth/signup'
    | '/candidate/applications'
    | '/candidate/events'
    | '/candidate/feedback'
    | '/candidate/history'
    | '/candidate/interviews'
    | '/candidate/jobs'
    | '/candidate/profile'
    | '/employer/analytics'
    | '/employer/candidates'
    | '/employer/company'
    | '/employer/events'
    | '/employer/feedback'
    | '/employer/interviews'
    | '/employer/jobs'
    | '/events/$id'
    | '/gate/$eventId'
    | '/admin/'
    | '/candidate/'
    | '/employer/'
    | '/admin/allocation/$eventId'
    | '/employer/events/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  ForCandidatesRoute: typeof ForCandidatesRoute
  ForEmployersRoute: typeof ForEmployersRoute
  RegisterCompanyRoute: typeof RegisterCompanyRoute
  AdminAccessRoute: typeof AdminAccessRoute
  AdminAutomationRoute: typeof AdminAutomationRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminCollaborationRoute: typeof AdminCollaborationRoute
  AdminCompanyRequestsRoute: typeof AdminCompanyRequestsRoute
  AdminDataRoute: typeof AdminDataRoute
  AdminEmployersRoute: typeof AdminEmployersRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminInterviewsRoute: typeof AdminInterviewsRoute
  AdminJobfairRoute: typeof AdminJobfairRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminQrRoute: typeof AdminQrRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStallsRoute: typeof AdminStallsRoute
  AttendPassIdRoute: typeof AttendPassIdRoute
  AuthAdminLoginRoute: typeof AuthAdminLoginRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CandidateApplicationsRoute: typeof CandidateApplicationsRoute
  CandidateEventsRoute: typeof CandidateEventsRoute
  CandidateFeedbackRoute: typeof CandidateFeedbackRoute
  CandidateHistoryRoute: typeof CandidateHistoryRoute
  CandidateInterviewsRoute: typeof CandidateInterviewsRoute
  CandidateJobsRoute: typeof CandidateJobsRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  EmployerAnalyticsRoute: typeof EmployerAnalyticsRoute
  EmployerCandidatesRoute: typeof EmployerCandidatesRoute
  EmployerCompanyRoute: typeof EmployerCompanyRoute
  EmployerEventsRoute: typeof EmployerEventsRouteWithChildren
  EmployerFeedbackRoute: typeof EmployerFeedbackRoute
  EmployerInterviewsRoute: typeof EmployerInterviewsRoute
  EmployerJobsRoute: typeof EmployerJobsRoute
  GateEventIdRoute: typeof GateEventIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CandidateIndexRoute: typeof CandidateIndexRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
  AdminAllocationEventIdRoute: typeof AdminAllocationEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-company': {
      id: '/register-company'
      path: '/register-company'
      fullPath: '/register-company'
      preLoaderRoute: typeof RegisterCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-employers': {
      id: '/for-employers'
      path: '/for-employers'
      fullPath: '/for-employers'
      preLoaderRoute: typeof ForEmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-candidates': {
      id: '/for-candidates'
      path: '/for-candidates'
      fullPath: '/for-candidates'
      preLoaderRoute: typeof ForCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/': {
      id: '/employer/'
      path: '/employer'
      fullPath: '/employer/'
      preLoaderRoute: typeof EmployerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/': {
      id: '/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof CandidateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate/$eventId': {
      id: '/gate/$eventId'
      path: '/gate/$eventId'
      fullPath: '/gate/$eventId'
      preLoaderRoute: typeof GateEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/employer/jobs': {
      id: '/employer/jobs'
      path: '/employer/jobs'
      fullPath: '/employer/jobs'
      preLoaderRoute: typeof EmployerJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/interviews': {
      id: '/employer/interviews'
      path: '/employer/interviews'
      fullPath: '/employer/interviews'
      preLoaderRoute: typeof EmployerInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/feedback': {
      id: '/employer/feedback'
      path: '/employer/feedback'
      fullPath: '/employer/feedback'
      preLoaderRoute: typeof EmployerFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/events': {
      id: '/employer/events'
      path: '/employer/events'
      fullPath: '/employer/events'
      preLoaderRoute: typeof EmployerEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/company': {
      id: '/employer/company'
      path: '/employer/company'
      fullPath: '/employer/company'
      preLoaderRoute: typeof EmployerCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/candidates': {
      id: '/employer/candidates'
      path: '/employer/candidates'
      fullPath: '/employer/candidates'
      preLoaderRoute: typeof EmployerCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/analytics': {
      id: '/employer/analytics'
      path: '/employer/analytics'
      fullPath: '/employer/analytics'
      preLoaderRoute: typeof EmployerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/jobs': {
      id: '/candidate/jobs'
      path: '/candidate/jobs'
      fullPath: '/candidate/jobs'
      preLoaderRoute: typeof CandidateJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/interviews': {
      id: '/candidate/interviews'
      path: '/candidate/interviews'
      fullPath: '/candidate/interviews'
      preLoaderRoute: typeof CandidateInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/history': {
      id: '/candidate/history'
      path: '/candidate/history'
      fullPath: '/candidate/history'
      preLoaderRoute: typeof CandidateHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/feedback': {
      id: '/candidate/feedback'
      path: '/candidate/feedback'
      fullPath: '/candidate/feedback'
      preLoaderRoute: typeof CandidateFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/events': {
      id: '/candidate/events'
      path: '/candidate/events'
      fullPath: '/candidate/events'
      preLoaderRoute: typeof CandidateEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/applications': {
      id: '/candidate/applications'
      path: '/candidate/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof CandidateApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/admin-login': {
      id: '/auth/admin-login'
      path: '/auth/admin-login'
      fullPath: '/auth/admin-login'
      preLoaderRoute: typeof AuthAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attend/$passId': {
      id: '/attend/$passId'
      path: '/attend/$passId'
      fullPath: '/attend/$passId'
      preLoaderRoute: typeof AttendPassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stalls': {
      id: '/admin/stalls'
      path: '/admin/stalls'
      fullPath: '/admin/stalls'
      preLoaderRoute: typeof AdminStallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/qr': {
      id: '/admin/qr'
      path: '/admin/qr'
      fullPath: '/admin/qr'
      preLoaderRoute: typeof AdminQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/admin/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jobfair': {
      id: '/admin/jobfair'
      path: '/admin/jobfair'
      fullPath: '/admin/jobfair'
      preLoaderRoute: typeof AdminJobfairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/interviews': {
      id: '/admin/interviews'
      path: '/admin/interviews'
      fullPath: '/admin/interviews'
      preLoaderRoute: typeof AdminInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employers': {
      id: '/admin/employers'
      path: '/admin/employers'
      fullPath: '/admin/employers'
      preLoaderRoute: typeof AdminEmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/admin/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/company-requests': {
      id: '/admin/company-requests'
      path: '/admin/company-requests'
      fullPath: '/admin/company-requests'
      preLoaderRoute: typeof AdminCompanyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collaboration': {
      id: '/admin/collaboration'
      path: '/admin/collaboration'
      fullPath: '/admin/collaboration'
      preLoaderRoute: typeof AdminCollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/admin/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/automation': {
      id: '/admin/automation'
      path: '/admin/automation'
      fullPath: '/admin/automation'
      preLoaderRoute: typeof AdminAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/admin/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/events/$id': {
      id: '/employer/events/$id'
      path: '/$id'
      fullPath: '/employer/events/$id'
      preLoaderRoute: typeof EmployerEventsIdRouteImport
      parentRoute: typeof EmployerEventsRoute
    }
    '/admin/allocation/$eventId': {
      id: '/admin/allocation/$eventId'
      path: '/admin/allocation/$eventId'
      fullPath: '/admin/allocation/$eventId'
      preLoaderRoute: typeof AdminAllocationEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface EmployerEventsRouteChildren {
  EmployerEventsIdRoute: typeof EmployerEventsIdRoute
}

const EmployerEventsRouteChildren: EmployerEventsRouteChildren = {
  EmployerEventsIdRoute: EmployerEventsIdRoute,
}

const EmployerEventsRouteWithChildren = EmployerEventsRoute._addFileChildren(
  EmployerEventsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  ForCandidatesRoute: ForCandidatesRoute,
  ForEmployersRoute: ForEmployersRoute,
  RegisterCompanyRoute: RegisterCompanyRoute,
  AdminAccessRoute: AdminAccessRoute,
  AdminAutomationRoute: AdminAutomationRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminCollaborationRoute: AdminCollaborationRoute,
  AdminCompanyRequestsRoute: AdminCompanyRequestsRoute,
  AdminDataRoute: AdminDataRoute,
  AdminEmployersRoute: AdminEmployersRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminInterviewsRoute: AdminInterviewsRoute,
  AdminJobfairRoute: AdminJobfairRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminQrRoute: AdminQrRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStallsRoute: AdminStallsRoute,
  AttendPassIdRoute: AttendPassIdRoute,
  AuthAdminLoginRoute: AuthAdminLoginRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  CandidateApplicationsRoute: CandidateApplicationsRoute,
  CandidateEventsRoute: CandidateEventsRoute,
  CandidateFeedbackRoute: CandidateFeedbackRoute,
  CandidateHistoryRoute: CandidateHistoryRoute,
  CandidateInterviewsRoute: CandidateInterviewsRoute,
  CandidateJobsRoute: CandidateJobsRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  EmployerAnalyticsRoute: EmployerAnalyticsRoute,
  EmployerCandidatesRoute: EmployerCandidatesRoute,
  EmployerCompanyRoute: EmployerCompanyRoute,
  EmployerEventsRoute: EmployerEventsRouteWithChildren,
  EmployerFeedbackRoute: EmployerFeedbackRoute,
  EmployerInterviewsRoute: EmployerInterviewsRoute,
  EmployerJobsRoute: EmployerJobsRoute,
  GateEventIdRoute: GateEventIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CandidateIndexRoute: CandidateIndexRoute,
  EmployerIndexRoute: EmployerIndexRoute,
  AdminAllocationEventIdRoute: AdminAllocationEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
